name: PR Status Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.3

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          for i in {1..20}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL Ready!"
              exit 0
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done
          echo "MySQL not ready"
          exit 1

      - name: Ensure Checks Table Exists
        run: |
          echo "Creating missing tables if necessary..."
          mysql -h "127.0.0.1" -u"${{ secrets.DB_USERNAME }}" -p"${{ secrets.DB_PASSWORD }}" -D "${{ secrets.DB_DATABASE }}" -e "
          CREATE TABLE IF NOT EXISTS Checks (
          checkId INT AUTO_INCREMENT PRIMARY KEY,
          datetime DATETIME NOT NULL
          ) ENGINE=InnoDB;
            SHOW TABLES;"

      - name: Run Tests # ✅ Fixed: Now actually runs something!
        env:
          DB_HOST: 127.0.0.1
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: root
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        run: |
          echo "Running tests with database connection..."
          npm test
