name: PR Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: WebApp Setup
    runs-on: ubuntu-latest

    services: #Extra Services
      mysql:
        image: mysql:8.0 #MySQL Container
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up environment variables
        working-directory: src
        run: |
          echo "DATABASE_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASS }}" >> .env

          echo "DATABASE_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "DIALECT=${{ secrets.DB_DIALECT }}" >> .env
          cat .env

      - name: Checking environment variables
        working-directory: src
        run: cat .env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: src
        run: npm install

      - name: Run Tests
        working-directory: src
        run: npm test
